a=[10,20,30,40,50,60,70,80,90,3,5,3,3,4,3,100]
a.append(110)                                                                                                                
print(a)                                                                                 
a.insert(1,77)                                                                                                                                                                         
print("The list afer adding an element at specified index : ",a)
b=[7,8,9]
a.extend(b)                                                                                                                   
print("The list after adding another list :",a)
print("The index of the element 100 is", a.index(100) )
a.sort()                                                                                                                      
print("The sorted list :", a)
a.reverse()                                                                                                                 
print("The reversed list :", a)
a.pop()                                                                                                                       
a.pop(8)                                                                                                                   
a.remove(30)                                                                                                            
print("The list after removing the element 30:",a)
print("The number of times the element 3 is repeated :",a.count(3))                      
c=a.copy()                                                                                                              
print(c)
print("Length of the List :",len(a))                                                                            
print("Minimum value in the list :",min(a))                                                       
print("Maximum value in the list :",max(a))                          
a.clear()                                                                                   
print(a)
del(a)
print(a)
